### ISSUE TITLE
How to set normalize_embeddings

### ISSUE THREAD

**Issue by wlleiiwang** [michaelfeil/embed#2]
When I use Batchference for sentence embedding，How to set normalize_embeddings=False：

https://github.com/michaelfeil/infinity/blob/main/libs/infinity_emb/infinity_emb/transformer/embedder/sentence_transformer.py#L118

**Comment by michaelfeil** [comment]
It's currently no possible. Generally, the magnitude of the embedding has little meaning - why are you interested? If you name a good reason, I'll maybe implement it.

**Comment by michaelfeil** [comment]
@wlleiiwang Can you elaborate please?
